### ISSUE TITLE
PR enquiry

### ISSUE THREAD

**Issue by oliverturner** [conferenceradar/list#18]
Would you be interested in a PR that centred the map on the visitor's location? The app's a bit frustrating if you aren't an American.

**Comment by ryanlanciaux** [comment]
This would be incredible!

**Comment by oliverturner** [comment]
Great! One thing before I start though: if we want to use the Location API to automatically determine the user's Lat/Long the site will need to run over HTTPS. Is this feasible?

A lighter-weight alternative would be to simply store the coordinates of the dragged map in localStorage and read from there on a repeat visit. I'll give that a shot in the meantime.

Thanks for the offer of help!

**Comment by ryanlanciaux** [comment]
I'm wondering if the lighter-weight alternative may be a good option right now. I will add HTTPS to the site but I'm trying to figure out the best path with gh-pages and custom domains. (_aside: it sounds like Cloudflare + changing everything over to use their DNS is the way that is commonly used but still researching this a bit_)

Would this local storage version still be useful if geolocation was turned on down the road? If so I think that would be excellent -- otherwise I'm definitely planning on adding SSL just still trying to find the best way.

**Comment by ryanlanciaux** [comment]
I may have spoken too soon -- I think https should be good-to-go on conferenceradar.com now

**Comment by joellanciaux** [comment]
@oliverturner Just to make sure before we make any updates that might impact the work that you're doing, what areas are you currently making changes in?

We're going to be refactoring things a bit and want to make sure we're minimizing conflicts, etc.!

(and super thanks for helping out -- this will be an awesome improvement!)

**Comment by ryanlanciaux** [comment]
This has been added to [conferenceradar](https://conferenceradar.com) -- sorry if you've been putting any work into this feature. 

Thanks again for bringing this up 👍

**Comment by oliverturner** [comment]
Not at all: thanks for adding it!
